name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: "github-ci@lumela-384408.iam.gserviceaccount.com"
        service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
        export_default_credentials: true

    - name: Configure Docker
      uses: docker/setup-docker@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/information-be:${{ github.sha }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/cloud-run-deploy@v1
      with:
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/information-be:${{ github.sha }}
        service_name: information-be
        region: us-central1
        platform: managed
        allow_unauthenticated: true
